global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'kafka-franz'
    static_configs:
      - targets: ['kafka-franz:8080']
  - job_name: 'docker'
    static_configs:
    - targets:
      -  192.168.1.129:9323
